### ISSUE TITLE
Errors following video example on new install, Max 8.13, High Sierra

### ISSUE THREAD

**Issue by iainctduncan** [Cycling74/max-test#21]
Hi folks, I followed the tutorial video and got some errors attempting to run the tests following the steps in the video. 

The first issue is just that the video is missing the critical step of making the max-test-config.json file. Maybe it can be updated or something added in the description? The error is not too obvious, without doing it I got:

Result:
	1: from /usr/local/lib/ruby/gems/2.5.0/gems/sqlite3-1.4.2/lib/sqlite3/database.rb:147:in `new'
/usr/local/lib/ruby/gems/2.5.0/gems/sqlite3-1.4.2/lib/sqlite3/database.rb:147:in `initialize': no such table: tests (SQLite3::SQLException)

After fixing this, I still got errors, though my tests worked. I'm not sure what happened, but it doesn't look like the clean output in the video.

Full Output:
`
MacBook-Pro-7:ruby iainduncan$ ruby test.rb "/Applications/"
Max Automated Test Runner
MAX FOLDER
/Applications
  Starting the OSC Server...

  Launching Max...
  Establishing Communication with Max...
2020-04-18 08:31:02.840 Max[63851:40438231] packages: package name (Video and Graphics) is different from folder name (Video & Graphics)
2020-04-18 08:31:02.853 Max[63851:40438231] packages: package name (Max-SDK) is different from folder name (max-sdk-8.0.3)
2020-04-18 08:31:03.745 Max[63851:40438231] max_startmaxserver
2020-04-18 08:31:04.536 Max[63851:40438231] clang using Sandy Bridge workaround
2020-04-18 08:31:04.709 Max[63851:40438231] sqlite version 3.8.5
2020-04-18 08:31:05.376 Max[63851:40438231] Max: starting maxdb update (schema version 8.1.2b)
2020-04-18 08:31:05.410 Max[63851:40438231] code: en-CA, name English
2020-04-18 08:31:06.806 Max[63851:40438231] test.port sending on 4792
2020-04-18 08:31:06.817 Max[63851:40438231] test.port listening on 4791
2020-04-18 08:31:06.977 Max[63851:40438231] maxworkspace_restore: vol=-674 filename=maxworkspace-63851.txt fullpath=Macintosh HD:/Users/iainduncan/Library/Application Support/Cycling '74/Max 8/Crash Recovery/maxworkspace-63851.txt
    Sending ping to Max.
/usr/local/lib/ruby/gems/2.5.0/gems/rosc-0.1.3/lib/osc.rb:297: warning: constant ::Fixnum is deprecated
    Ping successfully returned.

2020-04-18 08:31:09.429 Max[63851:40438451] Max: maxdb update complete
  Waiting for the Max database to complete...
    Sending query to Max.

  Telling Max to run all of the tests for us...
2020-04-18 08:31:29.599 Max[63851:40438231] doesn't understand "won't-understand-BOOGLE"
2020-04-18 08:31:30.041 Max[63851:40438231] index out of range for key test-
2020-04-18 08:31:30.515 Max[63851:40438231] @ loadbang: Kung
2020-04-18 08:31:30.515 Max[63851:40438231]
2020-04-18 08:31:30.515 Max[63851:40438231] @ set: Kung
2020-04-18 08:31:30.515 Max[63851:40438231]
2020-04-18 08:31:30.515 Max[63851:40438231] @ set: Fu
2020-04-18 08:31:30.515 Max[63851:40438231]
2020-04-18 08:31:31.303 Max[63851:40438231] ad_spin: looks like audio callbacks have stopped
2020-04-18 08:31:34.075 Max[63851:40438231] integration tests complete

  RESULTS

    Executed 9 Tests with 39 Assertions
    All assertions passed.  Congratulations!

pass
    Full test results can be found @
        /Volumes/Macintosh HD/Applications/Macintosh HD--Applications--maxtestresults.db3
    and explored in your favorite SQLite database client.

#<Thread:0x00007f7fdd86b9d8@test.rb:102 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	7: from test.rb:103:in `block in establishCommunication'
	6: from /usr/local/lib/ruby/gems/2.5.0/gems/rosc-0.1.3/lib/osc/udp.rb:18:in `serve'
	5: from /usr/local/lib/ruby/gems/2.5.0/gems/rosc-0.1.3/lib/osc/udp.rb:18:in `loop'
	4: from /usr/local/lib/ruby/gems/2.5.0/gems/rosc-0.1.3/lib/osc/udp.rb:20:in `block in serve'
	3: from /usr/local/lib/ruby/gems/2.5.0/gems/rosc-0.1.3/lib/osc/server.rb:33:in `dispatch'
	2: from /usr/local/lib/ruby/gems/2.5.0/gems/rosc-0.1.3/lib/osc.rb:242:in `decode'
	1: from /usr/local/lib/ruby/gems/2.5.0/gems/rosc-0.1.3/lib/osc.rb:242:in `new'
/usr/local/lib/ruby/gems/2.5.0/gems/rosc-0.1.3/lib/osc.rb:242:in `initialize': no implicit conversion of nil into String (TypeError)
`

**Comment by tap** [comment]
Thanks for the report. Is it also possible to share your OS version?

**Comment by iainctduncan** [comment]
Sure thing!
- OSX 10.13.4
- Ruby: ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin16]
let me know if there is more that would be helpful. 
thanks for the testing package, it's great!
