### ISSUE TITLE
Can't open a copy of Max with spaces in the filename

### ISSUE THREAD

**Issue by cassiel** [Cycling74/max-test#8]
Can't run on a Max with spaces in its name. (Probable cause: adoption of `IO.popen`.)

```
yedikule:ruby nick$ ruby test.rb "/Applications/Max bb_mxj_less.app/"
Max Automated Test Runner
  Starting the OSC Server...

  Launching Max...
test.rb:174:in `popen': No such file or directory - /Applications/Max (Errno::ENOENT)
    from test.rb:174:in `launchMax'
    from test.rb:194:in `<main>'
```

**Comment by benbrackenc74** [comment]
This seems fixed with more recent versions of max/max-test.
